name: PveAuction
version: ${version}
main: dev.narek.pveauction.PveAuctionPlugin
api-version: "1.21"
description: PvE аукцион — GUI и SQLite
authors: [narek]
softdepend: [Vault]

commands:
  ah:
    description: Аукцион
    usage: /ah [sell <цена>]
  admin:
    description: Админка сервера
    usage: /admin [give <ник> <сумма>]
  rtp:
    description: Телепорт в мир RTP
    usage: /rtp
  spawn:
    description: Вернуться на спавн
    usage: /spawn
  sethome:
    description: Установить дом
    usage: /sethome
  home:
    description: Телепорт домой
    usage: /home
  pay:
    description: Перевод денег
    usage: /pay <ник> <сумма>
  clan:
    description: Кланы
    usage: /clan <подкоманда>
  shop:
    description: Магазин и скупка
    usage: /shop

permissions:
  pveauction.use:
    description: Аукцион и продажа
    default: true
  pveauction.admin:
    description: Админка — креатив, выдача денег
    default: op
  pveauction.travel.rtp:
    description: Команда /rtp
    default: true
  pveauction.travel.spawn:
    description: Команда /spawn
    default: true
  pveauction.spawn.bypass:
    description: Строить и бить на спавне
    default: op
  pveauction.home:
    description: /sethome и /home
    default: true
  pveauction.pay:
    description: /pay
    default: true
  pveauction.clan:
    description: Команды клана
    default: true
  pveauction.shop:
    description: /shop
    default: true
